In [1]:
import joblib
import json

In [4]:
model = joblib.load(r"../../models/tuned/best_lightgbm_model.pkl")

In [6]:
feature_names = joblib.load(r"../../models/tuned/feature_names.pkl")
feature_names

['item_id',
 'dept_id',
 'cat_id',
 'store_id',
 'state_id',
 'wm_yr_wk',
 'weekday',
 'wday',
 'month',
 'year',
 'event_name_1',
 'event_type_1',
 'event_name_2',
 'event_type_2',
 'snap_CA',
 'snap_TX',
 'snap_WI',
 'sell_price',
 'lag_1',
 'lag_7',
 'lag_14',
 'lag_28',
 'rolling_mean_7',
 'rolling_std_7',
 'rolling_mean_14',
 'rolling_std_14',
 'rolling_mean_28',
 'rolling_std_28',
 'is_weekend',
 'price_lag_1',
 'price_diff_1',
 'price_pct_change',
 'price_max',
 'price_relative_to_max']

In [7]:
categorical_cols = joblib.load(r"../../models/tuned/categorical_cols.pkl")

In [12]:
import json

with open(
    r"../../models/tuned/best_metrics.json",
    "r"
) as f:
    metrics = json.load(f)

print(metrics)

{'RMSE': 1.2596662880136444, 'MAE': 0.4872918586763616}

In [13]:
print("Model Loaded Successfully")
print("Metrics:", metrics)
print("Features:", len(feature_names))
print("Categorical Columns:", len(categorical_cols))

Model Loaded Successfully
Metrics: {'RMSE': 1.2596662880136444, 'MAE': 0.4872918586763616}
Features: 34
Categorical Columns: 9

In [16]:
import joblib

# Load model
model = joblib.load(
    r"../../models/tuned/best_lightgbm_model.pkl"
)

# Load validation data
X_valid = joblib.load(
    r"../../models/tuned/X_valid.pkl"
)

y_valid = joblib.load(
    r"../../models/tuned/y_valid.pkl"
)

# Predictions
y_pred = model.predict(X_valid)

# Save predictions
joblib.dump(
    y_pred,
    r"../../models/tuned/y_pred.pkl"
)

print("Prediction Shape:", y_pred.shape)
print("Validation Shape:", y_valid.shape)

Prediction Shape: (4524000,)
Validation Shape: (4524000,)

In [17]:
import pandas as pd

comparison_df = pd.DataFrame({
    "Actual": y_valid.values[:20],
    "Predicted": y_pred[:20]
})

comparison_df["Error"] = (
    comparison_df["Actual"]
    - comparison_df["Predicted"]
)

comparison_df

    Actual  Predicted     Error
0        0   0.028702 -0.028702
1        0   0.028702 -0.028702
2        0   0.008814 -0.008814
3        0   0.010080 -0.010080
4        0   0.007301 -0.007301
5        0   0.013225 -0.013225
6        0   0.022243 -0.022243
7        0   0.036207 -0.036207
8        0   0.036207 -0.036207
9        0   0.021257 -0.021257
10       0   0.007301 -0.007301
11       0   0.012782 -0.012782
12       0   0.005043 -0.005043
13       0   0.023462 -0.023462
14       0   0.029245 -0.029245
15       0   0.029069 -0.029069
16       0   0.008989 -0.008989
17       0   0.005819 -0.005819
18       0  -0.002363  0.002363
19       0  -0.004599  0.004599

In [18]:
comparison_df.head(24)

    Actual  Predicted     Error
0        0   0.028702 -0.028702
1        0   0.028702 -0.028702
2        0   0.008814 -0.008814
3        0   0.010080 -0.010080
4        0   0.007301 -0.007301
5        0   0.013225 -0.013225
6        0   0.022243 -0.022243
7        0   0.036207 -0.036207
8        0   0.036207 -0.036207
9        0   0.021257 -0.021257
10       0   0.007301 -0.007301
11       0   0.012782 -0.012782
12       0   0.005043 -0.005043
13       0   0.023462 -0.023462
14       0   0.029245 -0.029245
15       0   0.029069 -0.029069
16       0   0.008989 -0.008989
17       0   0.005819 -0.005819
18       0  -0.002363  0.002363
19       0  -0.004599  0.004599

In [19]:
comparison_df[comparison_df["Actual"] != 0].head(20)

Empty DataFrame
Columns: [Actual, Predicted, Error]
Index: []

In [20]:
comparison_df[comparison_df["Actual"] > 0].head(20)

Empty DataFrame
Columns: [Actual, Predicted, Error]
Index: []

In [21]:
comparison_df = pd.DataFrame({
    "Actual": y_valid.values,
    "Predicted": y_pred
})

comparison_df["Error"] = (
    comparison_df["Actual"]
    - comparison_df["Predicted"]
)

comparison_df[comparison_df["Actual"] > 0].head(20)

     Actual  Predicted     Error
857       1   0.007301  0.992699
858       1   0.305265  0.694735
860       1   0.290271  0.709729
864       3   0.250181  2.749819
868       4   0.505362  3.494638
869       2   1.034758  0.965242
872       2   0.509247  1.490753
873       1   0.674721  0.325279
875       1   0.897815  0.102185
876       1   1.005977 -0.005977
881       1   0.554016  0.445984
883       1   0.686335  0.313665
884       1   0.635885  0.364115
885       2   0.644818  1.355182
886       2   0.731345  1.268655
888       1   0.771784  0.228216
889       2   1.082437  0.917563
890       3   1.217727  1.782273
891       1   1.178086 -0.178086
893       1   0.846532  0.153468

In [22]:
bias = (y_valid - y_pred).mean()

print("Bias:", bias)

Bias: -0.012075719936628242

In [23]:
residuals = y_valid - y_pred

print(residuals.describe())

count    4.524000e+06
mean    -1.207572e-02
std      1.259609e+00
min     -9.151582e+01
25%     -3.369233e-01
50%     -3.961410e-02
75%     -1.983829e-04
max      6.153893e+02
Name: sales, dtype: float64